
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import { config } from "dotenv";

// Load .env file explicitly
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // CLI commands (migrate / db push / introspect) MUST use a direct
    // connection — Supabase's port 6543 is a transaction-mode pgBouncer
    // pooler that does not support advisory locks or prepared statements.
    // Runtime Prisma Client will still pick up DATABASE_URL from schema.prisma.
    url: process.env.DIRECT_URL || env("DIRECT_URL"),
  },
});
